sudo: required
services:
    - docker

script: 
    - docker-compose build
    - docker-compose up -d
    - docker run --rm --network=qcubedexamples_default qcubedexamples_apache ./vendor/bin/codecept run
